repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.4.4
      hooks:
          - id: ruff
    - repo: https://github.com/astral-sh/pyright-pre-commit
      rev: v1.1.365
      hooks:
          - id: pyright
    # Pylance does not have a pre-commit hook; use Pyright for type checking (same engine)
    # Add more hooks below as needed
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
